stages:
  - build
  - unit-test
  - consumer-test
  - package
  - publish
  - can-i-deploy

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules


pact-publish:
  image:
    name: pactfoundation/pact-cli:latest
    entrypoint: [""]
  stage: publish
  script:
    - "pact publish pact/pacts
        --consumer-app-version=$CI_COMMIT_SHORT_SHA
        --tag=$CI_COMMIT_REF_NAME
        --broker-base-url=$PACT_BROKER_BASE_URL
        --broker-token=$PACT_BROKER_TOKEN"

can-i-deploy:
  stage: can-i-deploy
  image:
    name: pactfoundation/pact-cli:latest
    entrypoint: [""]
  environment:
    name: production
  only:
    refs:
      - main
  script:
    - "pact broker can-i-deploy
      --pacticipant=TodoService
      --version=$CI_COMMIT_SHORT_SHA
      --to=production
      --broker-base-url=$PACT_BROKER_BASE_URL
      --broker-token=$PACT_BROKER_TOKEN"
    - echo "Deploying ${CI_COMMIT_SHORT_SHA} to production!"
    - "pact broker create-version-tag
      --pacticipant=TodoApp
      --version=$CI_COMMIT_SHORT_SHA
      --tag=production
      --broker-base-url=$PACT_BROKER_BASE_URL
      --broker-token=$PACT_BROKER_TOKEN"



