stages:
  - build
  - test
  - publish
  - package
cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules

build:
  image: node:lts-alpine
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - "dist"

test:
  image: node:latest
  stage: test
  script:
    - yarn install
    - yarn test:unit

pact-publish:
  image:
    name: pactfoundation/pact-cli:latest
    entrypoint: [""]
  stage: publish
  script:
    - "pact publish pact/pacts 
        --consumer-app-version=$CI_COMMIT_SHORT_SHA 
        --tag=$CI_COMMIT_REF_NAME 
        --broker-base-url=$PACT_BROKER_BASE_URL 
        --broker-token=$PACT_BROKER_TOKEN"

package:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  needs:
    - pact-publish

