apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: todo-frontend
          image: registry.gitlab.com/modanisa-bootcamp/todo-frontend:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "300m"
          ports:
            - containerPort: 80
